In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

# Exercise 1:

In [2]:
A = np.array([
    [2,1,7],
    [1,9,4],
    [4,2,3]])
B = np.array([
    [1],
    [2],
    [3]
])
print(A)
print(A.shape)
print(B)
print(B.shape)


[[2 1 7]
 [1 9 4]
 [4 2 3]]
(3, 3)
[[1]
 [2]
 [3]]
(3, 1)


In [3]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.10160428, -0.05882353,  0.31550802],
       [-0.06951872,  0.11764706,  0.00534759],
       [ 0.18181818,  0.        , -0.09090909]])

In [4]:
r1 = A_inv @ B
r1

array([[ 0.72727273],
       [ 0.18181818],
       [-0.09090909]])

In [5]:
A @ r1

array([[1.],
       [2.],
       [3.]])

In [40]:
np.linalg.solve(A,B)

array([[ 0.72727273],
       [ 0.18181818],
       [-0.09090909]])

In [30]:
C = np.array([
    [5,2,3],
    [7,5,6],
    [1,2,9]])

D = np.array([
    [5],
    [6],
    [7]
])
print(C)
print(C.shape)
print(D)
print(D.shape)

[[5 2 3]
 [7 5 6]
 [1 2 9]]
(3, 3)
[[5]
 [6]
 [7]]
(3, 1)


In [31]:
C_inv = np.linalg.inv(C)
C_inv

array([[ 0.42307692, -0.15384615, -0.03846154],
       [-0.73076923,  0.53846154, -0.11538462],
       [ 0.11538462, -0.1025641 ,  0.14102564]])

In [32]:
r2 = C_inv @ D
r2

array([[ 0.92307692],
       [-1.23076923],
       [ 0.94871795]])

In [34]:
C @ r2

array([[5.],
       [6.],
       [7.]])

In [39]:
np.linalg.solve(C,D)

array([[ 0.92307692],
       [-1.23076923],
       [ 0.94871795]])