# Laboratory 6 : Matrices

## Task 1


Create a function named mat_desc() that througouhly describes a matrix, it should:

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix
  
Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline


Mat_A=np.array([[5,8,0],
                [3,2,1],
                [9,8,3]])

Mat_B=np.array([[6,4,3],
                [1,20,35],
                [15,7,2]])

Mat_C=np.array([[0,0,0],
                [0,0,0],
                [0,0,0],
                [0,0,0]])

Mat_D=np.array([[1,0,0],
                [0,1,0],
                [0,0,1]])

Mat_E=np.array([[1,1,1],
                [1,1,1],
                [1,1,1]])

def mat_desc(mat):
   print(f'{mat}\n\nShape: {mat.shape}\nSize: {np.product(mat.shape)}\nRank: {mat.ndim}\n')
   if mat.size > 0:
    square = True if mat.shape[0] == mat.shape[1] else False 
    identity = True if mat.shape[0] == mat.shape[1] and np.allclose(mat, np.identity(mat.shape[0])) else False
    ones = True if np.all((mat == 1)) else False 
    zero = True if np.all((mat == 0)) else False 
    print(f'Square Matrix: {square}\n'f'Identity Matrix: {identity}\n'f'Ones Matrix: {ones}\n'f'Zero Matrix: {zero}\n')
   else:
     print("Empty Matrix")

### Matrix A

In [2]:
mat_desc(Mat_A)

[[5 8 0]
 [3 2 1]
 [9 8 3]]

Shape: (3, 3)
Size: 9
Rank: 2

Square Matrix: True
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False



### Matrix B

In [3]:
mat_desc(Mat_B)

[[ 6  4  3]
 [ 1 20 35]
 [15  7  2]]

Shape: (3, 3)
Size: 9
Rank: 2

Square Matrix: True
Identity Matrix: False
Ones Matrix: False
Zero Matrix: False



### Matrix C

In [4]:
mat_desc(Mat_C)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]

Shape: (4, 3)
Size: 12
Rank: 2

Square Matrix: False
Identity Matrix: False
Ones Matrix: False
Zero Matrix: True



### Matrix D

In [5]:
mat_desc(Mat_D)

[[1 0 0]
 [0 1 0]
 [0 0 1]]

Shape: (3, 3)
Size: 9
Rank: 2

Square Matrix: True
Identity Matrix: True
Ones Matrix: False
Zero Matrix: False



### Matrix E

In [6]:
mat_desc(Mat_E)

[[1 1 1]
 [1 1 1]
 [1 1 1]]

Shape: (3, 3)
Size: 9
Rank: 2

Square Matrix: True
Identity Matrix: False
Ones Matrix: True
Zero Matrix: False



## Task 2


Create a function named mat_operations() that takes in two matrices or scalars a input parameters it should:

1. Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.
2. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
3. Returns the sum of the matrices.
4. Returns the differen of the matrices.
5. Returns the element-wise multiplication of the matrices.
6. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [7]:
def mat_operations(A,B):
    alpha=1**-10
    print(f'Matrices:\n\n{A},\n\n{B}')
    
    if(A.shape==B.shape):
            sum=A+B
            difference=A-B
            product=A*B
            quotient=A/(B+alpha)
            print("\n\n Sum:\n", sum)
            print("\n\n Difference:\n",difference)
            print("\n\n Product:\n",product)
            print("\n\n Quotient:\n",quotient)
            return
    else:
            print('\n\nUnable to perform operation due to incompatible matrices')
            return

## Matrix A and Matrix B

In [8]:
mat_operations(Mat_A,Mat_B)

Matrices:

[[5 8 0]
 [3 2 1]
 [9 8 3]],

[[ 6  4  3]
 [ 1 20 35]
 [15  7  2]]


 Sum:
 [[11 12  3]
 [ 4 22 36]
 [24 15  5]]


 Difference:
 [[ -1   4  -3]
 [  2 -18 -34]
 [ -6   1   1]]


 Product:
 [[ 30  32   0]
 [  3  40  35]
 [135  56   6]]


 Quotient:
 [[0.71428571 1.6        0.        ]
 [1.5        0.0952381  0.02777778]
 [0.5625     1.         1.        ]]


## Matrix B and Matrix C

In [9]:
mat_operations(Mat_B,Mat_C)

Matrices:

[[ 6  4  3]
 [ 1 20 35]
 [15  7  2]],

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


Unable to perform operation due to incompatible matrices


## Matrix B and Matrix D

In [10]:
mat_operations(Mat_B,Mat_D)

Matrices:

[[ 6  4  3]
 [ 1 20 35]
 [15  7  2]],

[[1 0 0]
 [0 1 0]
 [0 0 1]]


 Sum:
 [[ 7  4  3]
 [ 1 21 35]
 [15  7  3]]


 Difference:
 [[ 5  4  3]
 [ 1 19 35]
 [15  7  1]]


 Product:
 [[ 6  0  0]
 [ 0 20  0]
 [ 0  0  2]]


 Quotient:
 [[ 3.  4.  3.]
 [ 1. 10. 35.]
 [15.  7.  1.]]


## Matrix E and Matrix D

In [11]:
mat_operations(Mat_E,Mat_D)

Matrices:

[[1 1 1]
 [1 1 1]
 [1 1 1]],

[[1 0 0]
 [0 1 0]
 [0 0 1]]


 Sum:
 [[2 1 1]
 [1 2 1]
 [1 1 2]]


 Difference:
 [[0 1 1]
 [1 0 1]
 [1 1 0]]


 Product:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


 Quotient:
 [[0.5 1.  1. ]
 [1.  0.5 1. ]
 [1.  1.  0.5]]


## Matrix A and Matrix D

In [12]:
mat_operations(Mat_A,Mat_D)

Matrices:

[[5 8 0]
 [3 2 1]
 [9 8 3]],

[[1 0 0]
 [0 1 0]
 [0 0 1]]


 Sum:
 [[6 8 0]
 [3 3 1]
 [9 8 4]]


 Difference:
 [[4 8 0]
 [3 1 1]
 [9 8 2]]


 Product:
 [[5 0 0]
 [0 2 0]
 [0 0 3]]


 Quotient:
 [[2.5 8.  0. ]
 [3.  1.  1. ]
 [9.  8.  1.5]]
