In [1]:

import numpy as np 
import matplotlib.pyplot as plt


# Transposition

In [2]:

A = np.array([
    [5 ,1, 2],
    [6, 2, 1],
    [3, 9, 5] ])
A

array([[5, 1, 2],
       [6, 2, 1],
       [3, 9, 5]])

In [3]:
A1 = np.transpose(A)
A2 = A.T

In [4]:
np.array_equiv(A1,A2)

True

In [5]:
B = np.array(
    [[5,9,1,4],
     [10,5,2,1],
     [4,1,6,9]])
B.shape

(3, 4)

In [6]:
np.transpose(B).shape

(4, 3)

In [7]:
B.T.shape

(4, 3)

# Dot Product/Inner Product

In [8]:

A = np.array([
    [3,5,7],
    [2,1,9],
    [10,5,2]
])
B = np.array([
    [1,4,7],
    [2,3,2],
    [13,5,12]
])

In [9]:
np.dot(A,B)

array([[104,  62, 115],
       [121,  56, 124],
       [ 46,  65, 104]])

In [10]:

A.dot(B)

array([[104,  62, 115],
       [121,  56, 124],
       [ 46,  65, 104]])

In [11]:
A@B

array([[104,  62, 115],
       [121,  56, 124],
       [ 46,  65, 104]])

In [12]:
np.matmul(A,B)


array([[104,  62, 115],
       [121,  56, 124],
       [ 46,  65, 104]])

# Inner dimensions of the two matrices in question must be the same

In [21]:

A = np.array([
    [5,3,7],
    [3,2,9],
    [10,11,7]])
B = np.array([
    [5,4,1],
    [7,1,4],
    [2,11,17]])
C = np.array([
    [1,1,1],
    [3,3,3],
    [5,5,5],
    [2,2,2]])

print(A.shape)
print(B.shape)
print(C.shape)

(3, 3)
(3, 3)
(4, 3)


In [22]:
A@B

array([[ 60, 100, 136],
       [ 47, 113, 164],
       [141, 128, 173]])

In [23]:
A@C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

In [24]:
A@B.T

array([[ 44,  66, 162],
       [ 32,  59, 181],
       [101, 109, 260]])

# Dot product has special properties

In [17]:
A = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]])

B = np.array([
    [4,4,4],
    [5,5,5],
    [6,6,6]
])

C = np.array([
    [7,7,7],
    [8,8,8],
    [9,9,9]
])

In [18]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
matA = np.zeros(A.shape)

matA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
matA_dot = A.dot(np.zeros(A.shape))

matA_dot

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.array_equal(matA_dot,matA)

True

In [34]:
nullMat = np.empty(A.shape, dtype=float)
null = np.array(nullMat,dtype=float)
print(null)
np.allclose(matA_dot,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

# Determinant

In [25]:
A = np.array([
    [2,1,3],
    [5,6,7],
    [7,1,6]])

np.linalg.det(A)

-33.99999999999999

# Inverse

In [26]:
A = np.array([
    [53,1,9],
    [2,5,9],
    [9,3,5]])

np.array(A @ np.linalg.inv(A), dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])